### ISSUE TITLE
yarn build fails without NODE_OPTIONS=--openssl-legacy-provider

### ISSUE THREAD

**Issue by d3xt3r01** [ItsOnlyBinary/kiwiirc-plugin-tictactoe#7]
```
/kiwiirc-plugin-tictactoe # node --version
v18.17.0
```

```
/kiwiirc-plugin-tictactoe # yarn build
yarn run v1.22.19
$ webpack
/kiwiirc-plugin-tictactoe/node_modules/loader-runner/lib/LoaderRunner.js:133
                if(isError) throw e;
                            ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/kiwiirc-plugin-tictactoe/node_modules/webpack/lib/util/createHash.js:75:53)
    at NormalModule._initBuildHash (/kiwiirc-plugin-tictactoe/node_modules/webpack/lib/NormalModule.js:403:16)
    at handleParseError (/kiwiirc-plugin-tictactoe/node_modules/webpack/lib/NormalModule.js:451:10)
    at /kiwiirc-plugin-tictactoe/node_modules/webpack/lib/NormalModule.js:483:5
    at /kiwiirc-plugin-tictactoe/node_modules/webpack/lib/NormalModule.js:344:12
    at /kiwiirc-plugin-tictactoe/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/kiwiirc-plugin-tictactoe/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at iterateNormalLoaders (/kiwiirc-plugin-tictactoe/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /kiwiirc-plugin-tictactoe/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at context.callback (/kiwiirc-plugin-tictactoe/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at module.exports (/kiwiirc-plugin-tictactoe/node_modules/babel-loader/lib/index.js:183:8)
    at LOADER_EXECUTION (/kiwiirc-plugin-tictactoe/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/kiwiirc-plugin-tictactoe/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/kiwiirc-plugin-tictactoe/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (/kiwiirc-plugin-tictactoe/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/kiwiirc-plugin-tictactoe/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at /kiwiirc-plugin-tictactoe/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9
    at /kiwiirc-plugin-tictactoe/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.17.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This then hangs... reported in #6 

```
/kiwiirc-plugin-tictactoe # NODE_OPTIONS=--openssl-legacy-provider yarn build
yarn run v1.22.19
$ webpack
Hash: e02c57f94fbc9991b25d
Version: webpack 4.14.0
Time: 1103ms
Built at: 07/26/2023 10:00:44 PM
                  Asset      Size  Chunks             Chunk Names
    plugin-tictactoe.js  18.2 KiB       0  [emitted]  main
plugin-tictactoe.js.map  76.1 KiB       0  [emitted]  main
[1] ./tictactoe.js + 13 modules 27.6 KiB {0} [built]
    | ./tictactoe.js 6.94 KiB [built]
    | ./libs/Utils.js 1.67 KiB [built]
    | ./libs/TicTacToe.js 4.88 KiB [built]
    |     + 11 hidden modules
    + 6 hidden modules
```

**Comment by umutcaptain** [comment]
Hello to fix the problem

for linux & macos platform use this command at below :

export NODE_OPTIONS=--openssl-legacy-provider

for windows command prompt: 

set NODE_OPTIONS=--openssl-legacy-provider

for windows powershell : 

$env:NODE_OPTIONS = "--openssl-legacy-provider"

then yarn build will work perfectly.
